name = "TSMC Craft 21 Port"
author = "MikaAtom"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5319cbb83d21f4b4c8834a3c8ef30cca68bc049de9f39705dbc92d6691cf1b44"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
