name = "TSMC Craft 21 Port"
author = "MikaAtom"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a580578eb197d411589c93898f0b01e1c7b5c0ed5063a234426a9fe5f3c5bf5e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
