name = "TSMC Craft 21 Port"
author = "MikaAtom"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b45e0ee8aa640996a3ae089145678755388f272931bea3b0c3468d1c73fbfe27"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
